### ISSUE TITLE
Issue in webpack prevents use of amdefine and hence mscgenjs

### ISSUE THREAD

**Issue by parikshitgawali** [mscgenjs/mscgenjs-core#45]
mscgenjs is not compatible with webpack v3.6.0 .Getting error Uncaught Error: define cannot be used indirect . This is due to bug with webpack that 'define' is not support. Is it possible to make it compatible current version of webpack ?
{
"name": "mscgenjs",
"version": "1.9.0",
"description": "Implementation of MscGen in JavaScript",
"main": "index.js",
"dependencies": {
"amdefine": "1.0.1",
"requirejs": "2.3.2"
},

Working fine older"version": "1.12.15".

**Comment by sverweij** [comment]
This is caused by https://github.com/webpack/webpack/issues/5316 - which most likely affects all libraries that - just like mscgenjs - use amdefine to expose AMD modules for use in commonJS. Hence the ideal and correct solution for this would be for webpack to fix issue 5316. I see the issue is open since July 2017, though, so there's probably issues that have higher priority in the webpack project.

Alternatives:
- _Consumers using  mscgenjs i.c.w. webpack keep using webpack 1.x.x or migrate to another bundler_   
At least until webpack issue 5316 is solved. Not ideal, but in the short term (= the coming days) the only realistic 'solution' I can offer.
- _Change mscgenjs' module system to either commonjs or es6 modules._   
This is not a small change. I'd have to change some apps that depend on mscgenjs-core to keep them working, and I'd have to change my development workflow  (I've done this migration with sverweij/state-machine-cat a few weeks ago - and learned enough to know the issues mscgenjs would bump into). I might walk this path at some point in the future, but not now.
- _Hack around the webpack's module loader problems with [almond](https://github.com/requirejs/almond#exporting-a-public-api)._    
This looks promising, but I don't have experience with the solution outlined there (yet).

**Comment by sverweij** [comment]
@pgawali-broadsoft the workaround with almond seems to work ☝️. To use it you'll need to require the almond generated file in `dist/mscgen` instead of mscgen.js' root module - see the [samples/README.md](https://github.com/mscgenjs/mscgenjs-core/tree/feature/hack-around-webpack-bug/doc/samples/README.md) and the [sample root module](https://github.com/mscgenjs/mscgenjs-core/blob/feature/hack-around-webpack-bug/doc/samples/sample-webpack.js) for the setup I used to test this.

I'll need to test/ document and polish this before releasing (maybe this weekend, maybe later), but if you want to try it already checkout above branch and use the thing in `dist` or copy the workaround-with-almond thing in the dist folder of that feature branch directly from GitHub ([dist/mscgen.js](https://raw.githubusercontent.com/mscgenjs/mscgenjs-core/feature/hack-around-webpack-bug/dist/mscgen.js))

**Comment by parikshitgawali** [comment]
Thanks a lot . Issue mostly resolved but tool-tip functionality seems to be not working for me  .I can see 'title'tag  with populate text in DOM even though tool-tip is not visible on hover. Is it expected in this workaround?

**Comment by sverweij** [comment]
Tool-tip functionality should work as before. I've tested it in firefox 57, chrome 63 and safari 11 and there it works as expected.

(Note that browsers implement the tooltip on _text hover_ only, so if the label is super small or absent (e.g. `msc {a,b; a => b[title="Title won't show up on hover"];}`) getting the tool-tip to show will probably not be fruitful; but if there _is_ a label it will`msc {a,b; a => b[label="message in a bottle", title="Title will show up on hover"];}`.)

**Comment by sverweij** [comment]
I'll merge & publish this weekend - just a heads up: I've renamed the thing from `dist/mscgen.js` to `dist/webpack-issue-5316-workaround.js` because it's more clear & self documenting. So you'll use it like this:
```javascript
// commonjs, only for use with webpack > 2,
var msgenjs = require('mscgenjs/dist/webpack-issue-5316-workaround');
```

**Comment by parikshitgawali** [comment]
ok. Thanks for workaround. :)
